### ISSUE TITLE
Create PropertyWithinExpectedTest quality test

### ISSUE THREAD

**Issue by rete** [DQM4HEP/dqm4hep-core#30]
We need to create a quality test that unifies the idea of testing a property within an expected range. This could apply for : 
- Value (TScalar)
- Mean, Mean90 (TH1, TGraph)
- RMS, RMS90 (TH1, TGraph)
- Median (TH1, TGraph)
- Other ?

Can use a XML parameter to determine the strategies to adopt for testing the input element. For each of the possible strategies, define the range with a XML parameter
```xml
<parameter name="Properties"> Mean Mean90 </parameter>
<parameter name="MeanMin"> 0 </parameter>
<parameter name="MeanMax"> 10 </parameter>
<parameter name="Mean90Min"> 2 </parameter>
<parameter name="Mean90Max"> 8 </parameter>
```

**Comment by tcoates3** [comment]
I've already almost finished a test for the mean, mean90, rms, and rms90 within expected, using an analysis helper class, so I should be able to implement the others into it quickly.

**Comment by rete** [comment]
OK. Can you please combine them in a single qtest and make a pull request, even if it is not yet finished. You can mark it as WIP in the subject and continue updating it

**Comment by rete** [comment]
Done in https://github.com/DQM4HEP/dqm4hep-core/pull/32
